<?php $withDeadLine = $this->withDeadLine; ?>
<?php $timeLineData = $this->timeLineData; ?>
<?php $totalUtilization = $this->totalUtilization; ?>
<?php $utilization = round($this->utilization, 2) ; ?>
<?php $data = json_encode($timeLineData); ?>
<?php $tasks = $this->tasks; ?>
<?php $exactResponseTime = $this->exactResponseTime;?>
<?php $exactResponseTimeFlag = $this->exactResponseTimeFlag;?>
<div>
    <table id="data-table" style="padding-bottom: 30px;">
        <thead>
            <tr>
                <th>
                    Process
                </th>
                <th>
                    Period
                </th>
                <th>
                    Computation Time
                </th>
                <?php if ($withDeadLine): ?>
                    <th>
                        DeadLine
                    </th>
                <?php endif; ?>
                <th>
                    Utilization (%)
                </th>
            </tr>        
        </thead>
        <tbody>
            <?php foreach ($tasks as $task): ?>
                <tr>
                    <td>
                        <?php echo $task[0]; ?>
                    </td>
                    <td>
                        <?php echo $task[1]; ?>
                    </td>
                    <td>
                        <?php echo $task[2]; ?>
                    </td>
                    <?php if ($withDeadLine): ?>
                        <td>
                            <?php echo $task[3]; ?>
                        </td>
                    <?php endif; ?>
                    <td>
                        <?php echo $task[6]; ?>
                    </td>                
                </tr> 
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
if ($totalUtilization <= $utilization)
{
    $result =  " The Total Utilization is:" . $totalUtilization . " < " . $utilization . " (Lui Layland). Hence, Lui Layland criteria for scheduling is satisfied";
    $luilaylandIndex = 1;
} else
{
    $result = "The Total Utilization is: " . $totalUtilization . " > " . $utilization . " (Lui Layland). Hence, Lui Layland criteria for scheduling is not satisfied.";
    $luilaylandIndex = 0;
}
?>
<div style="<?php echo $luilaylandIndex ? 'color: green;' : 'color: red;'?>"><?php echo $result;?></div>
<div style="padding-top: 5px; padding-bottom: 25px; color: brown;">
    Task String: <span style="color: #333333; padding-left: 8px;"> <?php echo $this->taskString;?> </span>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization',
'version':'1','packages':['timeline']}]}"></script>
<script type="text/javascript">

            google.setOnLoadCallback(drawChart);
            function drawChart() {

            var container = document.getElementById('time-line');
                    var chart = new google.visualization.Timeline(container);
                    var dataTable = new google.visualization.DataTable();
                    dataTable.addColumn({ type: 'string', id: 'Name' });
                    dataTable.addColumn({ type: 'number', id: 'Start' });
                    dataTable.addColumn({ type: 'number', id: 'End' });
                    dataTable.addRows(<?php echo $data; ?>);
                    chart.draw(dataTable);
                    }
</script>
<div id="time-line" style="width: 1200px; height: <?php echo count($tasks) * 60 ?>px;"></div>
<span style="float: left; padding-top: 20px; width: 600px; <?php echo $exactResponseTimeFlag ? 'color: green;' : 'color: red;'?>">
    <span style="font-weight: bold;">(Exact) Response Time Analysis <?php echo $exactResponseTimeFlag ? '[ SCHEDULABLE ] ': '[ NOT SCHEDULABLE ] ';?></span><br>
    <?php foreach($exactResponseTime as $key => $rt):?>
        <?php foreach($rt as $k=>$itr):?>
            <?php echo $key.'['.$k.'] => '. $itr;?>
            <br>
        <?php endforeach;?>
    <?php endforeach;?>      
</span>

<?php if ($withDeadLine): ?>
<span style="float:left; padding-top: 20px; width: 600px; <?php echo $this->simplifiedResponseTimeFlag ? 'color: green;' : 'color: red;'?>">
    <span style="font-weight: bold;">(Simplified) Response Time Analysis <?php echo $this->simplifiedResponseTimeFlag ? '[ SCHEDULABLE ] ': '[ NOT SCHEDULABLE ] ';?></span><br>
    <?php foreach($this->simplifiedResponseTime as $key => $rt):?>        
        <?php echo $key.' => '. $rt;?>
        <br>        
    <?php endforeach;?>      
</span>
<?php endif;?>